-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.CharType exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


simple : Translations -> String
simple translations =
    t translations "charType.simple"


compound : Translations -> String
compound translations =
    t translations "charType.compound"
