-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.OrientationType exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


horizontal : Translations -> String
horizontal translations =
    t translations "orientationType.horizontal"


vertical : Translations -> String
vertical translations =
    t translations "orientationType.vertical"
