-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.PeriodName exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


shang : Translations -> String
shang translations =
    t translations "periodName.shang"


westernZhou : Translations -> String
westernZhou translations =
    t translations "periodName.westernZhou"


springAndAutumn : Translations -> String
springAndAutumn translations =
    t translations "periodName.springAndAutumn"


warringStates : Translations -> String
warringStates translations =
    t translations "periodName.warringStates"
