-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.ScriptName exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


oracle : Translations -> String
oracle translations =
    t translations "scriptName.oracle"


bronze : Translations -> String
bronze translations =
    t translations "scriptName.bronze"


seal : Translations -> String
seal translations =
    t translations "scriptName.seal"
