-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.StageName exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


early : Translations -> String
early translations =
    t translations "stageName.early"


middle : Translations -> String
middle translations =
    t translations "stageName.middle"


late : Translations -> String
late translations =
    t translations "stageName.late"
