-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.StrokeLineCapType exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


round : Translations -> String
round translations =
    t translations "strokeLineCapType.round"


square : Translations -> String
square translations =
    t translations "strokeLineCapType.square"
