-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


preferences : Translations -> String
preferences translations =
    t translations "preferences"


strokeWidth : Translations -> String
strokeWidth translations =
    t translations "strokeWidth"


snapToGrid : Translations -> String
snapToGrid translations =
    t translations "snapToGrid"


showReference : Translations -> String
showReference translations =
    t translations "showReference"


previewInParagraph : Translations -> String
previewInParagraph translations =
    t translations "previewInParagraph"


language : Translations -> String
language translations =
    t translations "language"


writeTextHereToPreview : Translations -> String
writeTextHereToPreview translations =
    t translations "writeTextHereToPreview"


doYouWantToDelete : Translations -> String
doYouWantToDelete translations =
    t translations "doYouWantToDelete"


thisCannotBeUndone : Translations -> String
thisCannotBeUndone translations =
    t translations "thisCannotBeUndone"


allCharsOfAType : Translations -> String -> String
allCharsOfAType translations charType =
    tr translations Curly "allCharsOfAType" [ ( "charType", charType ) ]


character : Translations -> String
character translations =
    t translations "character"


acceptOnlyOneCharacter : Translations -> String
acceptOnlyOneCharacter translations =
    t translations "acceptOnlyOneCharacter"


cannotContainSelfReference : Translations -> String
cannotContainSelfReference translations =
    t translations "cannotContainSelfReference"


characterNotFound : Translations -> String -> String
characterNotFound translations char =
    tr translations Curly "characterNotFound" [ ( "char", char ) ]


explaination : Translations -> String
explaination translations =
    t translations "explaination"


referenceImage : Translations -> String
referenceImage translations =
    t translations "referenceImage"


period : Translations -> String
period translations =
    t translations "period"


stage : Translations -> String
stage translations =
    t translations "stage"


origin : Translations -> String
origin translations =
    t translations "origin"


url : Translations -> String
url translations =
    t translations "url"
