-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


preferences : Translations -> String
preferences translations =
    t translations "preferences"


strokeWidth : Translations -> String
strokeWidth translations =
    t translations "strokeWidth"


strokeLineCap : Translations -> String
strokeLineCap translations =
    t translations "strokeLineCap"


snapToGrid : Translations -> String
snapToGrid translations =
    t translations "snapToGrid"


previewInParagraph : Translations -> String
previewInParagraph translations =
    t translations "previewInParagraph"


writeTextHereToPreview : Translations -> String
writeTextHereToPreview translations =
    t translations "writeTextHereToPreview"


doYouWantToDelete : Translations -> String
doYouWantToDelete translations =
    t translations "doYouWantToDelete"


thisCannotBeUndone : Translations -> String
thisCannotBeUndone translations =
    t translations "thisCannotBeUndone"


allCharsOfAType : Translations -> String -> String
allCharsOfAType translations charType =
    tr translations Curly "allCharsOfAType" [ ( "charType", charType ) ]


character : Translations -> String
character translations =
    t translations "character"


acceptOnlyOneCharacter : Translations -> String
acceptOnlyOneCharacter translations =
    t translations "acceptOnlyOneCharacter"
